# Урок 2. Метрики качества классификации ч.1

В уроке мы разбирали матрицу ошибок и некоторые метрики, основанные на терминах матрицы ошибок. Здесь же посмотрим, как эти метрики применять на практике и что  по ним можно выяснить.

### 1.1
Выкачайте тренировочный датасет Titanic - train.csv - с сайта [kaggle](https://www.kaggle.com/c/titanic/data). С помощью функции pd.read_csv() загрузите данные в датафрейм. Выведите первые 20 строк и проанализируйте данные: какие колонки присутствуют (более конкретная информация по ним есть на сайте kaggle), каким образом в них обозначены данные и какие типы данных используются (используйте pandas.dtypes).

In [1]:
import pandas as pd

In [2]:
### YOUR CODE HERE ###
titanic_train = pd.read_csv('data/train.csv')
print(titanic_train.dtypes)
titanic_train.head(20)

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C

### 1.2
Проверьте, имеются ли пропущенные значения в колонках, и выведите сумму всех пропущенных значений в каждой из колонок.

In [3]:
### YOUR CODE HERE ###

# Проверка пропущенных значений по колонкам
missing_values = titanic_train.isna().sum()

print("Количество пропущенных значений в каждой колонке:")
print(missing_values)

Количество пропущенных значений в каждой колонке:
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

### 1.3
Замените все пропущенные значения колонки Age на медианы в зависимости от пола человека: т.е. если пол человека в строке с пропущенным значением "male", заменяете пропущенное значение возраста на медиану по всем известным возрастам мужчин, и наоборот. Выведите медианы возраста в зависимости от пола. Пропущенные значения колонок Cabin и Embarked замените на U (Unknown).

Примечание: для группировки по полу можно использовать метод df.groupby(), который имеет встроенные агрегатные функции (в т.ч. для вычисления медианы).  Для установки пропущенных значений в датасете воспользуйтесь функцией df.apply().

In [4]:
### YOUR CODE HERE ###
print(titanic_train[titanic_train['Sex'] == 'male']['Age'].median())
print(titanic_train[titanic_train['Sex'] == 'female']['Age'].median())
median = titanic_train.groupby('Sex')['Age'].median()
print(median)

# 2. Заменяем пропущенные значения Age на медиану по полу
titanic_train['Age'] = titanic_train.apply(
    lambda row: median[row['Sex']] if pd.isna(row['Age']) else row['Age'],
    axis=1
)

# 3. Заменяем пропущенные значения в Cabin и Embarked на 'U'
titanic_train[['Cabin', 'Embarked']] = titanic_train[['Cabin', 'Embarked']].fillna('U')

# Результат
titanic_train.head(40)

29.0
27.0
Sex
female    27.0
male      29.0
Name: Age, dtype: float64

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,U,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,U,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,U,S
5,6,0,3,"Moran, Mr. James",male,29.0,0,0,330877,8.4583,U,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,U,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,U,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,U,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,U,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,U,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,U,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,U,S
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,U,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,29.0,0,0,244373,13.0000,U,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,U,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,27.0,0,0,2649,7.2250,U,C
20,21,0,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0000,U,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,8.0292,U,Q
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
24,25,0,3,"Palsson, Miss. Torborg Danira",female,8.0,3,1,349909,21.0750,U,S
25,26,1,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,38.0,1,5,347077,31.3875,U,S
26,27,0,3,"Emir, Mr. Farred Chehab",male,29.0,0,0,2631,7.2250,U,C
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,27.0,0,0,330959,7.8792,U,Q
29,30,0,3,"Todoroff, Mr. Lalio",male,29.0,0,0,349216,7.8958,U,S
30,31,0,1,"Uruchurtu, Don. Manuel E",male,40.0,0,0,PC 17601,27.7208,U,C
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,27.0,1,0,PC 17569,146.5208,B78,C
32,33,1,3,"Glynn, Miss. Mary Agatha",female,27.0,0,0,335677,7.7500,U,Q
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,U,S
34,35,0,1,"Meyer, Mr. Edgar Joseph",male,28.0,1,0,PC 17604,82.1708,U,C
35,36,0,1,"Holverson, Mr. Alexander Oskar",male,42.0,1,0,113789,52.0000,U,S
36,37,1,3,"Mamee, Mr. Hanna",male,29.0,0,0,2677,7.2292,U,C
37,38,0,3,"Cann, Mr. Ernest Charles",male,21.0,0,0,A./5. 2152,8.0500,U,S
38,39,0,3,"Vander Planke, Miss. Augusta Maria",female,18.0,2,0,345764,18.0000,U,S
39,40,1,3,"Nicola-Yarred, Miss. Jamila",female,14.0,1,0,2651,11.2417,U,C

### 1.4
Выведите возраст пассажиров с PassengerID = [6, 20]. Убедитесь, что заполнены все пропущенные значения (воспользуйтесь функцией df.isnull() ).

In [5]:
### YOUR CODE HERE ###
t = titanic_train[titanic_train['PassengerId'].isin([6, 20])][['PassengerId', 'Sex', 'Age']]
print("\nВозраст пассажиров с PassengerId 6 и 20:\n", t)

Возраст пассажиров с PassengerId 6 и 20:
     PassengerId     Sex   Age
5             6    male  29.0
19           20  female  27.0

Так как не все классификаторы могут работать с категориальными признаками, в данном случае необходимо заменить их на числовые.

Также можно было бы выделить расширенные признаки, такие как статус пассажира (Mr., Mrs., Miss., Dr., Master. и т.д.), собственный индекс билета, индекс палубы и другие, но здесь ограничимся выбором более простых признаков.

### 1.5
В колонке Sex замените значения на 0, если пол "male", и на 1, если "female". В колонке Embarked замените параметры "U", "S", "C", "Q" на 0, 1, 2, 3 соответственно. Отбросьте колонки PassengerId, Name, Ticket, Cabin. Выведите первые 20 строк получившегося набора данных.

In [6]:
### YOUR CODE HERE ###
# 🔄 Заменим значения в колонке Sex
titanic_train['Sex'] = titanic_train['Sex'].map({'male': 0, 'female': 1})

# 🔄 Заменим значения в колонке Embarked
titanic_train['Embarked'] = titanic_train['Embarked'].map({'U': 0, 'S': 1, 'C': 2, 'Q': 3})

# 🧹 Удалим лишние колонки
titanic_train = titanic_train.drop(columns=['PassengerId', 'Name', 'Ticket', 'Cabin'])

titanic_train.head(20)

    Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0          0       3    0  22.0      1      0   7.2500         1
1          1       1    1  38.0      1      0  71.2833         2
2          1       3    1  26.0      0      0   7.9250         1
3          1       1    1  35.0      1      0  53.1000         1
4          0       3    0  35.0      0      0   8.0500         1
5          0       3    0  29.0      0      0   8.4583         3
6          0       1    0  54.0      0      0  51.8625         1
7          0       3    0   2.0      3      1  21.0750         1
8          1       3    1  27.0      0      2  11.1333         1
9          1       2    1  14.0      1      0  30.0708         2
10         1       3    1   4.0      1      1  16.7000         1
11         1       1    1  58.0      0      0  26.5500         1
12         0       3    0  20.0      0      0   8.0500         1
13         0       3    0  39.0      1      5  31.2750         1
14         0       3    1  14.0      0      0   7.8542         1
15         1       2    1  55.0      0      0  16.0000         1
16         0       3    0   2.0      4      1  29.1250         3
17         1       2    0  29.0      0      0  13.0000         1
18         0       3    1  31.0      1      0  18.0000         1
19         1       3    1  27.0      0      0   7.2250         2

### 1.6
Приступим к построению классификаторов. **Условимся, что, если функция или объект модели имеют параметр random_state, то устанавливаем его равным 17 в каждом из случаев.**

Разделите данные на тренировочный и тестовый датасеты, установив размер тестового как 0.25 (первая колонка Survived является целевой, поэтому необходимо сначала ее отделить от признаков).

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
### YOUR CODE HERE ###
x_train, x_test, y_train, y_test = train_test_split(titanic_train.iloc[:,1:],
                                                    titanic_train['Survived'],
                                                    test_size=0.25,
                                                    random_state=17)

### 1.7
Обучите на полученных выборках несколько классификаторов, которые импортированы ниже.

**Примечание: в методе ближайших соседей используйте количество соседей, равное 5.**

In [11]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression

In [27]:
### YOUR CODE HERE ###
knn = KNeighborsClassifier(n_neighbors=5)
knn_model = knn.fit(x_train, y_train)
knn_y_pred = knn.predict(x_test)

nb = GaussianNB()
nb_model = nb.fit(x_train, y_train)
nb_predict = nb.predict(x_test)


dtc = DecisionTreeClassifier(random_state=17)
dtc_model = dtc.fit(x_train, y_train)
dtc_predictions = dtc.predict(x_test)

lr = LogisticRegression(random_state=17)
lr_model = lr.fit(x_train, y_train)
lr_predictions = lr.predict(x_test)

Очевидно, в этом случае использовать метрику accuracy, которую мы применяли до этого, не совсем правильно: она не даст верную оценку классификатору, потому как выживших явно меньше, чем погибших.

Вспомним про такие метрики как точность и полнота. Здесь они подойдут хорошо, так как у нас имеются положительный и отрицательный классы, и определить корректно один из них может оказаться более важным .

### 1.8
В каждом из пунктов следующего теста выберите, что важнее максимизировать: точность (precision) или полноту (recall). Выпишите ответы.

1. Вероятность того, что при определенной поломке самолета он сможет долететь до пункта назначения (1 - долетел, 0 - не долетел).
2. Предсказание, представляет ли человек опасность, по анализу психического состояния (1 - представляет опасность, 0 - не представляет опасности).
3. Предсказание ухода клиента (1 - клиент ушел, 0 - остался).
4. Выявление рака на основе медицинских показателей (1 - болен раком, 0 - здоров).
5. Предсказание летальности при наблюдаемой мутации (1 - выживание, 0 - летальный исход).
6. Определение важности происшествия для экстренных служб (1 - важно, 0 - неважно).
7. Окупятся ли вложения в бизнес (1 - окупятся, 0 - не окупятся).

Ваш ответ:

1. Важно минимизировать FP, т.к.  важнее выявить ложные долёты, т.е. берем precision<br>
2. Важно минимизировать FN, берем полноту<br>
3. Важно минимизировать FN, берем полноту<br>
4. Важно минимизировать FN, берем полноту<br>
5. Важно минимизировать FN, берем полноту<br>
6. Важно минимизировать FN, берем полноту<br>
7. Важно минимизировать FP, берем precision<br>

### 1.9
Определите, что важнее использовать в случае датасета Titanic: полноту или точность. Объясните, почему.

### 1.10
Для каждого классификатора выведите матрицу ошибок и самостоятельно рассчитайте метрику recall (расчеты должны присутствовать). Проверьте расчеты, воспользовавшись встроенной метрикой recall_score.

In [13]:
from sklearn.metrics import confusion_matrix, recall_score

In [31]:
### YOUR CODE HERE ###
cm_knn = confusion_matrix(y_test, knn_y_pred)
print(cm_knn)
recall_knn_my = cm_knn[0, 0]/(cm_knn[0, 0] + cm_knn[0, 1])
recall_knn = recall_score(y_test, knn_y_pred)
print("recall_knn_my: ", recall_knn_my)
print("recall_knn: ", recall_knn)

cm_nb = confusion_matrix(y_test, nb_predict)
print(cm_nb)
recall_nb_my = cm_nb[0, 0]/(cm_nb[0, 0] + cm_nb[0, 1])
recall_nb = recall_score(y_test, nb_predict)
print("recall_nb_my: ", recall_nb_my)
print("recall_nb: ", recall_nb)

cm_dtc = confusion_matrix(y_test, dtc_predictions)
print(cm_dtc)
recall_dtc_my = cm_dtc[0, 0]/(cm_dtc[0, 0] + cm_dtc[0, 1])
recall_dtc = recall_score(y_test, dtc_predictions)
print("recall_dtc_my: ", recall_dtc_my)
print("recall_dtc: ", recall_dtc)

cm_lr = confusion_matrix(y_test, lr_predictions)
print(cm_lr)
recall_lr_my = cm_lr[0, 0]/(cm_lr[0, 0] + cm_lr[0, 1])
recall_lr = recall_score(y_test, lr_predictions)
print("recall_lr_my: ", recall_lr_my)
print("recall_lr: ", recall_lr)

[[110  21]
 [ 47  45]]
recall_knn_my:  0.8396946564885496
recall_knn:  0.4891304347826087
[[111  20]
 [ 27  65]]
recall_nb_my:  0.8473282442748091
recall_nb:  0.7065217391304348
[[112  19]
 [ 26  66]]
recall_dtc_my:  0.8549618320610687
recall_dtc:  0.717391304347826
[[114  17]
 [ 28  64]]
recall_lr_my:  0.8702290076335878
recall_lr:  0.6956521739130435

### 1.11
Выберите ту модель, на которой метрика recall давала лучший ответ, и рассчитайте для нее precision, используя встроенную функцию.

In [32]:
from sklearn.metrics import precision_score

In [33]:
### YOUR CODE HERE ###
precission_dtc_my = precision_score(y_test, dtc_predictions)
print("precission_dtc_my: ", precission_dtc_my)

precission_dtc_my:  0.7764705882352941